### ISSUE TITLE
Give an option to run the game fullscreen

### ISSUE THREAD

**Issue by Mayank0255** [Amegma/Galaxy-Attack#19]

**Comment by lyu4321** [comment]
Hey @Mayank0255, I'd like to work on this issue. Could you assign it to me?

**Comment by Mayank0255** [comment]
@lyu4321 go ahead, I just wanna tell you that after the screen is fullscreen the the aspect ratio of the screens should be the same and the extra space on both the side should be blank, or the screen will become very big and it would take a lot of time to reach from one end of the screen to another

**Comment by Mayank0255** [comment]
@lyu4321 to get the pr counted for the fest you will need to get it merged by the end of tomorrow, so I recommend speed it up so that I can review it asap and merge it if it's good enough and btw after that a special mention will also be done on twitter via my personal account

**Comment by lyu4321** [comment]
@Mayank0255 Thank you! I've created a [PR](https://github.com/Mayank0255/Atari-Space-Invaders/pull/23) for this issue.

**Comment by Mayank0255** [comment]
@lyu4321 thanks will just take a look
