### ISSUE TITLE
Game breaks on non-windows machines

### ISSUE THREAD

**Issue by nkitsaini** [Amegma/Galaxy-Attack#65]
The breakage is caused by following line. `windll` is windows only interface.
https://github.com/Amegma/Galaxy-Attack/blob/310479c63c63e1625e4e65fc08bafa3d85aafdda/config.py#L19

Other then this everything seems to work:
* Mouse control
* Sound
* Animations

**Comment by naddoska** [comment]
Hey there :)
I actually made a fix for this: 
https://github.com/Amegma/Galaxy-Attack/pull/66 
have fun :)
